In [1]:
import torch
import numpy as np
import sklearn
from sklearn import *
import pandas as pd
import matplotlib.pyplot as plt
from fhrr import FHRR_Model
from sklearn.metrics import confusion_matrix

In [2]:
coll = np.array(pd.read_csv("./data/parsed_college_data.csv"))
# first 8 columns of matrix are considered parameters
# the last one is considered to be the class
X = np.array(coll[:, :10])
Y = np.array(coll[:, 10])

In [3]:
X, X_test, Y, Y_test = sklearn.model_selection.train_test_split(X, Y)
print(type(X[0]), X[0])
X = torch.Tensor(X.astype('float64'))
Y = torch.Tensor(Y.astype('int64'))
X_test = torch.Tensor(X_test.astype('float64'))
Y_test = torch.Tensor(Y_test.astype('int64'))

print("X train shape", X.shape, "Y train shape", Y.shape)
print("X test shape", X_test.shape, "Y Test shape", Y_test.shape)

<class 'numpy.ndarray'> [0 1 1 0 0 48 7700000 67.0 88.34 1]
X train shape torch.Size([750, 10]) Y train shape torch.Size([750])
X test shape torch.Size([250, 10]) Y Test shape torch.Size([250])


In [4]:
classes = len(np.unique(Y))
features = X.shape[1]
print("Number of classes", classes, '\nNumber of features', features)
dim = 1000

Number of classes 2 
Number of features 10


In [5]:
model = FHRR_Model(classes, features, dim, pw='uniform')
# model.set_train_set(X, Y)
model.encode_set(X, Y)

model.train()

preds = [model.predict(model.encode(x)) for x in X_test]
acc = sklearn.metrics.accuracy_score(Y_test, preds)
print("One pass training", acc)
print(confusion_matrix(Y_test, preds))

model.retrain(40)
preds = [model.predict(model.encode(x)) for x in X_test]
acc = sklearn.metrics.accuracy_score(Y_test, preds)
print("Iterative training", acc)
print(confusion_matrix(Y_test, preds))

X train shape (750, 1000)
One pass training 0.672
[[74 46]
 [36 94]]
Iterative training 0.48
[[57 63]
 [67 63]]


In [6]:
model = FHRR_Model(classes, features, dim, pw='normal')
# model.set_train_set(X, Y)
model.encode_set(X, Y)

model.train()

preds = [model.predict(model.encode(x)) for x in X_test]
acc = sklearn.metrics.accuracy_score(Y_test, preds)
print("One pass training", acc)
print(confusion_matrix(Y_test, preds))
model.retrain(200)

preds = [model.predict(model.encode(x)) for x in X_test]
acc = sklearn.metrics.accuracy_score(Y_test, preds)
print("Iterative training", acc)
print(confusion_matrix(Y_test, preds))

X train shape (750, 1000)
One pass training 0.672
[[71 49]
 [33 97]]
Iterative training 0.504
[[58 62]
 [62 68]]
